tovp/gifts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url

from . import views


gift = [
    url(
        regex=r'^$',
        view=views.GiftListView.as_view(),
        name='index'
    ),
    # URL pattern for the GiftDetailView
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.GiftDetailView.as_view(),
        name='detail',
    ),
    # URL pattern for the GiftCreateView
    url(
        regex=r'^create/$',
        view=views.GiftCreateView.as_view(),
        name='create',
    ),
    # URL pattern for the GiftUpdateView
    url(
        regex=r'^(?P<pk>\d+)/edit$',
        view=views.GiftUpdateView.as_view(),
        name='update',
    ),
]

gift_given = [
    # URL pattern for the GiftDetailView
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.GiftGivenDetailView.as_view(),
        name='detail',
    ),
    # URL pattern for the GiftCreateView
    url(
        regex=r'^create/(?P<person_id>\d+)/$',
        view=views.GiftGivenCreateView.as_view(),
        name='create',
    ),
    # URL pattern for the GiftUpdateView
    url(
        regex=r'^(?P<person_id>\d+)/(?P<pk>\d+)/edit$',
        view=views.GiftGivenUpdateView.as_view(),
        name='update',
    ),
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.GiftGivenDeleteView.as_view(),
        name="delete",
    ),
]

urlpatterns = [
    url(r'^gift/', include(gift, namespace="gift")),
    url(r'^gift_given/', include(gift_given, namespace="gift_given")),
]

tovp/tovp/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = [
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),

    url(r'^', include("donate.urls", namespace="donate")),
    url(r'^donor-list', include("donor_list.urls", namespace="donor_list")),

    url(r'^database/', include("search.urls", namespace="search")),
    url(r'^database/contacts/', include("contacts.urls", namespace="contacts")),
    url(r'^database/promotions/', include("promotions.urls",
                                          namespace="promotions")),
    url(r'^database/gifts/', include("gifts.urls", namespace="gifts")),
    url(r'^database/contributions/', include("contributions.urls",
                                             namespace="contributions")),

    url(r'^hijack/', include('hijack.urls')),
    url(r'^attachments/', include('attachments.urls')),
    url(r'^ajax_select/lookups/', include(ajax_select_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tovp/contacts/models.py
import datetime
import re

from django.conf import settings
from django.db import models
from django.db.models import permalink
from django.utils.translation import ugettext_lazy as _, pgettext_lazy as __
from django.utils.functional import cached_property
from django.core import exceptions
from django.apps import apps

from django.core.validators import RegexValidator

from django_countries.fields import CountryField

from model_utils.models import TimeStampedModel
from audit_log.models import AuthStampedModel

from ananta.models import NextPrevMixin


class Person(AuthStampedModel, NextPrevMixin, TimeStampedModel):
    def reindex_related(self):
        related = []
        for pledge in self.pledges.all():
            related.append(pledge)
        return related

    # title of the person
    MR, MISS, MRS, MS, DR = ('Mr', 'Miss', 'Mrs', 'Ms', 'Dr')
    TITLE_CHOICES = (
        (MR, _("Mr")),
        (MISS, _("Miss")),
        (MRS, _("Mrs")),
        (MS, _("Ms")),
        (DR, _("Dr")),
    )

    # Regex for each country. Not listed countries don't use postcodes
    # Based on http://en.wikipedia.org/wiki/List_of_postal_codes
    POSTCODES_REGEX = {
        'AC': r'^[A-Z]{4}[0-9][A-Z]$',
        'AD': r'^AD[0-9]{3}$',
        'AF': r'^[0-9]{4}$',
        'AI': r'^AI-2640$',
        'AL': r'^[0-9]{4}$',
        'AM': r'^[0-9]{4}$',
        'AR': r'^([0-9]{4}|[A-Z][0-9]{4}[A-Z]{3})$',
        'AS': r'^[0-9]{5}(-[0-9]{4}|-[0-9]{6})?$',
        'AT': r'^[0-9]{4}$',
        'AU': r'^[0-9]{4}$',
        'AX': r'^[0-9]{5}$',
        'AZ': r'^AZ[0-9]{4}$',
        'BA': r'^[0-9]{5}$',
        'BB': r'^BB[0-9]{5}$',
        'BD': r'^[0-9]{4}$',
        'BE': r'^[0-9]{4}$',
        'BG': r'^[0-9]{4}$',
        'BH': r'^[0-9]{3,4}$',
        'BL': r'^[0-9]{5}$',
        'BM': r'^[A-Z]{2}([0-9]{2}|[A-Z]{2})',
        'BN': r'^[A-Z}{2}[0-9]]{4}$',
        'BO': r'^[0-9]{4}$',
        'BR': r'^[0-9]{5}(-[0-9]{3})?$',
        'BT': r'^[0-9]{3}$',
        'BY': r'^[0-9]{6}$',
        'CA': r'^[A-Z][0-9][A-Z][0-9][A-Z][0-9]$',
        'CC': r'^[0-9]{4}$',
        'CH': r'^[0-9]{4}$',
        'CL': r'^([0-9]{7}|[0-9]{3}-[0-9]{4})$',
        'CN': r'^[0-9]{6}$',
        'CO': r'^[0-9]{6}$',
        'CR': r'^[0-9]{4,5}$',
        'CU': r'^[0-9]{5}$',
        'CV': r'^[0-9]{4}$',
        'CX': r'^[0-9]{4}$',
        'CY': r'^[0-9]{4}$',
        'CZ': r'^[0-9]{5}$',
        'DE': r'^[0-9]{5}$',
        'DK': r'^[0-9]{4}$',
        'DO': r'^[0-9]{5}$',
        'DZ': r'^[0-9]{5}$',
        'EC': r'^EC[0-9]{6}$',
        'EE': r'^[0-9]{5}$',
        'EG': r'^[0-9]{5}$',
        'ES': r'^[0-9]{5}$',
        'ET': r'^[0-9]{4}$',
        'FI': r'^[0-9]{5}$',
        'FK': r'^[A-Z]{4}[0-9][A-Z]{2}$',
        'FM': r'^[0-9]{5}(-[0-9]{4})?$',
        'FO': r'^[0-9]{3}$',
        'FR': r'^[0-9]{5}$',
        'GA': r'^[0-9]{2}.*[0-9]{2}$',
        'GB': r'^[A-Z][A-Z0-9]{1,3}[0-9][A-Z]{2}$',
        'GE': r'^[0-9]{4}$',
        'GF': r'^[0-9]{5}$',
        'GG': r'^([A-Z]{2}[0-9]{2,3}[A-Z]{2})$',
        'GI': r'^GX111AA$',
        'GL': r'^[0-9]{4}$',
        'GP': r'^[0-9]{5}$',
        'GR': r'^[0-9]{5}$',
        'GS': r'^SIQQ1ZZ$',
        'GT': r'^[0-9]{5}$',
        'GU': r'^[0-9]{5}$',
        'GW': r'^[0-9]{4}$',
        'HM': r'^[0-9]{4}$',
        'HN': r'^[0-9]{5}$',
        'HR': r'^[0-9]{5}$',
        'HT': r'^[0-9]{4}$',
        'HU': r'^[0-9]{4}$',
        'ID': r'^[0-9]{5}$',
        'IL': r'^[0-9]{7}$',
        'IM': r'^IM[0-9]{2,3}[A-Z]{2}$$',
        'IN': r'^[0-9]{6}$',
        'IO': r'^[A-Z]{4}[0-9][A-Z]{2}$',
        'IQ': r'^[0-9]{5}$',
        'IR': r'^[0-9]{5}-[0-9]{5}$',
        'IS': r'^[0-9]{3}$',
        'IT': r'^[0-9]{5}$',
        'JE': r'^JE[0-9]{2}[A-Z]{2}$',
        'JM': r'^JM[A-Z]{3}[0-9]{2}$',
        'JO': r'^[0-9]{5}$',
        'JP': r'^[0-9]{3}-?[0-9]{4}$',
        'KE': r'^[0-9]{5}$',
        'KG': r'^[0-9]{6}$',
        'KH': r'^[0-9]{5}$',
        'KR': r'^[0-9]{3}-?[0-9]{3}$',
        'KY': r'^KY[0-9]-[0-9]{4}$',
        'KZ': r'^[0-9]{6}$',
        'LA': r'^[0-9]{5}$',
        'LB': r'^[0-9]{8}$',
        'LI': r'^[0-9]{4}$',
        'LK': r'^[0-9]{5}$',
        'LR': r'^[0-9]{4}$',
        'LS': r'^[0-9]{3}$',
        'LT': r'^(LT-)?[0-9]{5}$',
        'LU': r'^[0-9]{4}$',
        'LV': r'^LV-[0-9]{4}$',
        'LY': r'^[0-9]{5}$',
        'MA': r'^[0-9]{5}$',
        'MC': r'^980[0-9]{2}$',
        'MD': r'^MD-?[0-9]{4}$',
        'ME': r'^[0-9]{5}$',
        'MF': r'^[0-9]{5}$',
        'MG': r'^[0-9]{3}$',
        'MH': r'^[0-9]{5}$',
        'MK': r'^[0-9]{4}$',
        'MM': r'^[0-9]{5}$',
        'MN': r'^[0-9]{5}$',
        'MP': r'^[0-9]{5}$',
        'MQ': r'^[0-9]{5}$',
        'MT': r'^[A-Z]{3}[0-9]{4}$',
        'MV': r'^[0-9]{4,5}$',
        'MX': r'^[0-9]{5}$',
        'MY': r'^[0-9]{5}$',
        'MZ': r'^[0-9]{4}$',
        'NA': r'^[0-9]{5}$',
        'NC': r'^[0-9]{5}$',
        'NE': r'^[0-9]{4}$',
        'NF': r'^[0-9]{4}$',
        'NG': r'^[0-9]{6}$',
        'NI': r'^[0-9]{3}-[0-9]{3}-[0-9]$',
        'NL': r'^[0-9]{4}[A-Z]{2}$',
        'NO': r'^[0-9]{4}$',
        'NP': r'^[0-9]{5}$',
        'NZ': r'^[0-9]{4}$',
        'OM': r'^[0-9]{3}$',
        'PA': r'^[0-9]{6}$',
        'PE': r'^[0-9]{5}$',
        'PF': r'^[0-9]{5}$',
        'PG': r'^[0-9]{3}$',
        'PH': r'^[0-9]{4}$',
        'PK': r'^[0-9]{5}$',
        'PL': r'^[0-9]{2}-?[0-9]{3}$',
        'PM': r'^[0-9]{5}$',
        'PN': r'^[A-Z]{4}[0-9][A-Z]{2}$',
        'PR': r'^[0-9]{5}$',
        'PT': r'^[0-9]{4}(-?[0-9]{3})?$',
        'PW': r'^[0-9]{5}$',
        'PY': r'^[0-9]{4}$',
        'RE': r'^[0-9]{5}$',
        'RO': r'^[0-9]{6}$',
        'RS': r'^[0-9]{5}$',
        'RU': r'^[0-9]{6}$',
        'SA': r'^[0-9]{5}$',
        'SD': r'^[0-9]{5}$',
        'SE': r'^[0-9]{5}$',
        'SG': r'^([0-9]{2}|[0-9]{4}|[0-9]{6})$',
        'SH': r'^(STHL1ZZ|TDCU1ZZ)$',
        'SI': r'^(SI-)?[0-9]{4}$',
        'SK': r'^[0-9]{5}$',
        'SM': r'^[0-9]{5}$',
        'SN': r'^[0-9]{5}$',
        'SV': r'^01101$',
        'SZ': r'^[A-Z][0-9]{3}$',
        'TC': r'^TKCA1ZZ$',
        'TD': r'^[0-9]{5}$',
        'TH': r'^[0-9]{5}$',
        'TJ': r'^[0-9]{6}$',
        'TM': r'^[0-9]{6}$',
        'TN': r'^[0-9]{4}$',
        'TR': r'^[0-9]{5}$',
        'TT': r'^[0-9]{6}$',
        'TW': r'^[0-9]{5}$',
        'UA': r'^[0-9]{5}$',
        'US': r'^[0-9]{5}(-[0-9]{4}|-[0-9]{6})?$',
        'UY': r'^[0-9]{5}$',
        'UZ': r'^[0-9]{6}$',
        'VA': r'^00120$',
        'VC': r'^VC[0-9]{4}',
        'VE': r'^[0-9]{4}[A-Z]?$',
        'VG': r'^VG[0-9]{4}$',
        'VI': r'^[0-9]{5}$',
        'VN': r'^[0-9]{6}$',
        'WF': r'^[0-9]{5}$',
        'XK': r'^[0-9]{5}$',
        'YT': r'^[0-9]{5}$',
        'ZA': r'^[0-9]{4}$',
        'ZM': r'^[0-9]{5}$',
    }

    title = models.CharField(
        __(u"Treatment Pronouns for the contact", u"Title"),
        max_length=64, choices=TITLE_CHOICES, blank=True)

    # legal name
    first_name = models.CharField(
        max_length=100, blank=True,
        help_text=_('Enter your first name.'))
    middle_name = models.CharField(
        max_length=100, blank=True,
        help_text=_('Enter your middle name.'))
    last_name = models.CharField(
        max_length=100, blank=True,
        help_text=_('Enter your surname.'))

    initiated_name = models.CharField(
        max_length=100, blank=True,
        help_text=_('Spiritual name if you have e.g: Krishna Das, Tulasi Dasi, '
                    'Bhakta Burfi')
    )

    email = models.EmailField("Email", max_length=200, blank=True)

    phone_number = models.CharField(
        max_length=100, blank=True,
        help_text='Enter your phone number. If it is a non-Indian number '
                  'please use the international format e.g.: +421 222 333 444')

    temple = models.CharField(
        max_length=100, blank=True,
        help_text=_('If person tells you association with temple, please enter '
                    'it here.')
    )

    # Following 5 fields are all part of the address
    address = models.TextField(
        _("Address"), max_length=255, blank=True)
    city = models.CharField(_("City"), max_length=255, blank=True)
    state = models.CharField(_("State/County"), max_length=255, blank=True)
    postcode = models.CharField(_("Post/Zip-code"), max_length=64, blank=True)
    country = CountryField()

    pan_card_number = models.CharField(
        _('PAN card number'), max_length=50, blank=True, null=True,
        validators=[
            RegexValidator(
                regex='[A-Za-z]{5}\d{4}[A-Za-z]{1}',
                message='Seems like invalid PAN Card Number.',
                code='invalid_pan_number'
            ),
        ],
        help_text=_('Required for Indian citizens. Enter your PAN card number.')
    )
    YATRA_CHOICES = (
        ('middle-east', _('Middle East')),
        ('north-america', _('North America')),
        ('russia', _('Russia')),
        ('south-africa', _('South Africa')),
        ('uk', _('UK')),
    )
    yatra = models.CharField(
        "Yatra", max_length=100, choices=YATRA_CHOICES, blank=True, null=True,
        help_text=_('If person belongs to one the of yatras in drowpdown, '
                    'please choose it'))

    location = models.CharField(_("Collection Location"), max_length=100,
                                blank=True)
    old_database_id = models.IntegerField(
        _('Old Database ID'), blank=True, null=True,
        help_text=_('If you are transfering data from old database (CiviCRM), '
                    'enter contact_id here. Otherwise leave empty.'))

    note = models.TextField(_("Note"), blank=True)

    def clean(self):
        # Strip all whitespace
        for field in ['first_name', 'middle_name', 'last_name',
                      'initiated_name', 'address', 'city',
                      'state', 'postcode', 'pan_card_number']:
            if self.__dict__[field]:

tovp/gifts/forms.py
from django import forms

from contacts.models import Person

from .models import Gift, GiftGiven


class GiftForm(forms.ModelForm):
    class Meta:
        model = Gift
        exclude = ('status_changed',)


class GiftGivenForm(forms.ModelForm):
    person = forms.ModelChoiceField(queryset=Person.objects.all(),
                                    widget=forms.HiddenInput())

    class Meta:
        model = GiftGiven
        exclude = ('status_changed',)

tovp/gifts/views.py
# -*- coding: utf-8 -*-
# view imports
from django.views.generic import DetailView, UpdateView, ListView
from django.views.generic.edit import CreateView, DeleteView
from django.contrib import messages
from django.utils.translation import ugettext as _

# Only authenticated users can access views using this.
from braces.views import LoginRequiredMixin, PermissionRequiredMixin

from ananta.models import RevisionCommentMixin
from contacts.models import Person

from .models import Gift, GiftGiven
from .forms import GiftForm, GiftGivenForm


class GiftListView(LoginRequiredMixin, ListView):
    model = Gift
    template_name = 'gifts/gift_list.html'


class GiftDetailView(LoginRequiredMixin, DetailView):
    model = Gift
    template_name = 'gifts/gift_detail.html'


class GiftCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Gift
    permission_required = "gifts.add_gift"
    template_name = 'gifts/gift_form.html'
    form_class = GiftForm

    def get_context_data(self, **kwargs):
        context = super(GiftCreateView, self).get_context_data(**kwargs)
        context['content_title'] = _("Add new gift")
        return context


class GiftUpdateView(RevisionCommentMixin, LoginRequiredMixin,
                     PermissionRequiredMixin, UpdateView):
    model = Gift
    permission_required = "gifts.change_gift"
    template_name = 'gifts/gift_form.html'
    form_class = GiftForm

    def get_context_data(self, **kwargs):
        context = super(GiftUpdateView, self).get_context_data(**kwargs)
        context['content_title'] = _("Edit gift")
        return context


class GiftGivenDetailView(LoginRequiredMixin, DetailView):
    model = GiftGiven
    template_name = 'gifts/gift_given_detail.html'


class GiftGivenCreateView(LoginRequiredMixin, PermissionRequiredMixin,
                          CreateView):
    model = GiftGiven
    permission_required = "gifts.add_giftgiven"
    template_name = 'gifts/gift_given_form.html'
    form_class = GiftGivenForm

    def get_initial(self):
        initial = super(GiftGivenCreateView, self).get_initial()
        initial = initial.copy()
        initial['person'] = self.kwargs.get('person_id')
        return initial

    def get_context_data(self, **kwargs):
        context = super(GiftGivenCreateView, self).get_context_data(**kwargs)
        context['content_title'] = _("Add new gift")
        person = Person.objects.get(pk=self.kwargs.get('person_id'))
        context['person'] = person
        return context


class GiftGivenUpdateView(RevisionCommentMixin, LoginRequiredMixin,
                          PermissionRequiredMixin, UpdateView):
    model = GiftGiven
    permission_required = "gifts.change_giftgiven"
    template_name = 'gifts/gift_given_form.html'
    form_class = GiftGivenForm

    def get_context_data(self, **kwargs):
        context = super(GiftGivenUpdateView, self).get_context_data(**kwargs)
        context['content_title'] = _("Edit gift")
        person = Person.objects.get(pk=self.kwargs.get('person_id'))
        context['person'] = person
        return context


class GiftGivenDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = "gifts.delete_giftgiven"
    template_name = 'promotions/confirm_delete.html'
    model = GiftGiven

    def get_success_url(self):
        return self.get_object().person.get_absolute_url()

    def delete(self, request, *args, **kwargs):
        success_message = "%s has been deleted successfully" % \
            self.get_object()._meta.verbose_name.title()
        messages.success(self.request, success_message)
        return super(GiftGivenDeleteView, self).delete(request, *args, **kwargs)

tovp/gifts/templates/gifts/gift_detail.html
{% extends 'content-area.html' %}
{% set page_title = object.name %}
{% set body_class = "person-detail" %}

{% macro print_field(label, value) -%}
    <div class="field-label">{{ label }}</div>
    <div class="field-value">{{ value or 'N/A' }}</div>
{%- endmacro %}

{% block page_content %}
<div class="row">
    <div class="{% if user.has_perm('gifts.change_gift') %} col-xs-9 col-ms-10 col-sm-11{% else %}col-xs-12{% endif %}">
        <h1>{{ object.name }}</h1>
    </div>
    {% if user.has_perm('gifts.change_gift') %} 
        <div class="col-xs-3 col-ms-2 col-sm-1">
            <a href="{{ url('gifts:gift:update', object.pk) }}" class="btn btn-lg btn-warning">Edit</a>
        </div>
    {% endif %}

    {% set field_label = 'Description' %}
    {% set field_name = 'description' %}
    {% if object[field_name] %}
    <div class="col-xs-12">
        {{ print_field(field_label, object[field_name])}}
    </div>
    {% endif %}

    {% set field_label = 'Yatra' %}
    {% set field_name = 'yatra' %}
    {% if object[field_name] %}
    <div class="col-xs-12">
        <div class="field-label">{{ field_label }}</div>
        <div class="field-value">
            {{ object.get_yatra_display() }}
        </div>
    </div>
    {% endif %}

    {% include '_nextprev.html' %}
</div>
{% endblock %}

tovp/gifts/templates/gifts/gift_form.html
{% extends 'content-area.html' %}
{% set body_class = "profiles edit-profile" %}

{% block javascript_head %}
    {{ super() }}
    {% include '_import-selectize.html' %}
{% endblock %}

{% block page_content %}
    {# <script src="{{ static('js/jquery.formset.js') }}"></script> #}

    <form action="" enctype="multipart/form-data" method="post">{{ csrf() }}
        {{ form.media }}
        {% if form.non_field_errors() %}
            <p class="tooltip error">
                {{ form.non_field_errors() }}
            </p>
        {% endif %}

        <div class="row">
            {% for field_name in ['name', 'description'] %}
            <div class="col-xs-12 form-group{{' has-error' if form[field_name].errors }}">
                <label class="control-label" for="inputSuccess1">{{ form[field_name].label }}</label>
                {{form[field_name]|add_css('form-control')}}
                {% if form[field_name].help_text %}
                {{ form[field_name].errors|safe }}
                    <div class="help-text">
                        {{ form[field_name].help_text }}
                    </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <input class="btn btn-lg btn-success" type="submit" value="Save" /> 
    </form>

<script>
    // Disables 'enter' key to submit form
    function checkEnter(e){
        e = e || event;
        var txtArea = /textarea/i.test((e.target || e.srcElement).tagName);
        return txtArea || (e.keyCode || e.which || e.charCode || 0) !== 13;
    }
    document.querySelector('form').onkeypress = checkEnter;
</script>
<script>
    $('.is-selectize').selectize()
</script>
{% endblock %}

tovp/gifts/templates/gifts/gift_given_detail.html
{% extends 'content-area.html' %}
{% set page_title = object.name %}
{% set body_class = "person-detail" %}

{% macro print_field(label, value) -%}
    <div class="field-label">{{ label }}</div>
    <div class="field-value">{{ value or 'N/A' }}</div>
{%- endmacro %}

{% block page_content %}
<div class="row">
    <div class="{% if user.has_perm('gifts.change_gift') %} col-xs-9 col-ms-10 col-sm-11{% else %}col-xs-12{% endif %}">
        <h1>{{ object.gift.name }}</h1>
    </div>
    {% if user.has_perm('gifts.change_gift') %} 
        <div class="col-xs-3 col-ms-2 col-sm-1">
            <a href="{{ url('gifts:gift_given:update', object.person.pk, object.pk) }}" class="btn btn-lg btn-warning">Edit</a>
        </div>
    {% endif %}

    <div class="col-xs-12">
        <div class="field-label">Given to:</div>
        <div class="field-value">
            <a href="{{ object.person.get_absolute_url() }}">{{ object.person.full_name }}{% if object.person.full_name and object.person.initiated_name %} - {% endif %}{{ object.person.initiated_name }}</a>
        </div>
    </div>

    {% set field_label = 'Status' %}
    {% set field_name = 'status' %}
    {% if object[field_name] %}
    <div class="col-xs-6">
        {{ print_field(field_label, object.get_status_display()) }}
    </div>
    {% endif %}

    {% set field_label = 'On' %}
    {% set field_name = 'status_changed' %}
    {% if object[field_name] %}
    <div class="col-xs-6">
        <div class="field-label">{{ field_label }}:</div>
        <div class="field-value">
            {{ object[field_name]|datetimeformat }} ({{ object[field_name]|timesince }} ago)
        </div>
    </div>
    {% endif %}

    {% set field_label = 'Note' %}
    {% set field_name = 'note' %}
    {% if object[field_name] %}
    <div class="col-xs-12">
        {{ print_field(field_label, object[field_name])}}
    </div>
    {% endif %}

    {% include '_nextprev.html' %}
</div>
{% endblock %}

tovp/gifts/templates/gifts/gift_given_form.html
{% extends 'content-area.html' %}
{% set body_class = "profiles edit-profile" %}

{% block javascript_head %}
    {{ super() }}
    {% include '_import-selectize.html' %}
{% endblock %}

{% block page_content %}
    {# <script src="{{ static('js/jquery.formset.js') }}"></script> #}

    <form action="" enctype="multipart/form-data" method="post">{{ csrf() }}
        {{ form.media }}
        {% if form.non_field_errors() %}
            <p class="tooltip error">
                {{ form.non_field_errors() }}
            </p>
        {% endif %}

        {{form['person']}}
        <div class="row">
            <div class="col-xs-12 form-group">
                <label class="control-label">Donor Name:</label>
                <h2>{{ person.mixed_name }}</h2>
            </div>

            {% for field_name in ['gift', 'status', 'note'] %}
            <div class="col-xs-12 form-group{{' has-error' if form[field_name].errors }}">
                <label class="control-label" for="inputSuccess1">{{ form[field_name].label }}</label>
                {{form[field_name]|add_css('form-control')}}
                {% if form[field_name].help_text %}
                {{ form[field_name].errors|safe }}
                    <div class="help-text">
                        {{ form[field_name].help_text }}
                    </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <input class="btn btn-lg btn-success" type="submit" value="Save" /> 
        {% if object and user.has_perm('gifts.delete_giftgiven') %}
            <a href="{{ url('gifts:gift_given:delete', object.pk) }}" class="btn btn-large">Delete Gift Given</a>
        {% endif %}
    </form>

<script>
    // Disables 'enter' key to submit form
    function checkEnter(e){
        e = e || event;
        var txtArea = /textarea/i.test((e.target || e.srcElement).tagName);
        return txtArea || (e.keyCode || e.which || e.charCode || 0) !== 13;
    }
    document.querySelector('form').onkeypress = checkEnter;
</script>
<script>
    $('.is-selectize').selectize()
</script>
{% endblock %}