tovp/attachments/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^add-for/(?P<app_label>[\w\-]+)/(?P<model_name>[\w\-]+)/(?P<pk>\d+)/$',
        views.add_attachment,
        name="add_attachment"),
    url(
        r'^delete/(?P<attachment_pk>\d+)/$',
        views.delete_attachment,
        name="delete_attachment"),
]

tovp/tovp/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from ajax_select import urls as ajax_select_urls

admin.autodiscover()

urlpatterns = [
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),

    url(r'^', include("donate.urls", namespace="donate")),
    url(r'^donor-list', include("donor_list.urls", namespace="donor_list")),

    url(r'^database/', include("search.urls", namespace="search")),
    url(r'^database/contacts/', include("contacts.urls", namespace="contacts")),
    url(r'^database/promotions/', include("promotions.urls",
                                          namespace="promotions")),
    url(r'^database/gifts/', include("gifts.urls", namespace="gifts")),
    url(r'^database/contributions/', include("contributions.urls",
                                             namespace="contributions")),

    url(r'^hijack/', include('hijack.urls')),
    url(r'^attachments/', include('attachments.urls')),
    url(r'^ajax_select/lookups/', include(ajax_select_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tovp/attachments/models.py
import os
from datetime import datetime

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils.translation import ugettext_lazy as _

from model_utils.models import TimeStampedModel
from audit_log.models import AuthStampedModel


class AttachmentManager(models.Manager):
    def attachments_for_object(self, obj):
        object_type = ContentType.objects.get_for_model(obj)
        return self.filter(content_type__pk=object_type.id,
                           object_id=obj.id)


class Attachment(TimeStampedModel, AuthStampedModel):
    def attachment_upload(instance, filename):
        """Stores the attachment in a "per module/appname/primary key" folder"""

        return 'attachments/%s/%s/%s' % (
            '%s_%s' % (instance.content_object._meta.app_label,
                       instance.content_object._meta.object_name.lower()),
            instance.content_object.pk,
            datetime.now().strftime("%Y%m%d%H%M-%f") + os.path.splitext(filename)[1])

    objects = AttachmentManager()

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    attachment_file = models.FileField('attachment', upload_to=attachment_upload)
    description = models.CharField(max_length=255, blank=True)

    ATTACHMENT_TYPE_CHOICES = (
        ('passport', _('Passport')),
        ('cheque', _('Cheque')),
        ('other', _('Other Document')),
    )
    attachment_type = models.CharField(
        "Attachment Type", max_length=50, choices=ATTACHMENT_TYPE_CHOICES)

    class Meta:
        # ordering = ['-created']
        permissions = (
            ('delete_foreign_attachments', 'Can delete foreign attachments'),
        )

    def __str__(self):
        return 'Attached file: %s' % self.attachment_type

    @property
    def filename(self):
        return os.path.split(self.attachment_file.name)[1]

tovp/attachments/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from attachments.models import Attachment


class AttachmentForm(forms.ModelForm):
    attachment_file = forms.FileField(label=_('Upload attachment'))

    class Meta:
        model = Attachment
        fields = ('attachment_type', 'attachment_file', 'description')

    def save(self, request, obj, *args, **kwargs):
        self.instance.content_type = ContentType.objects.get_for_model(obj)
        self.instance.object_id = obj.id
        super(AttachmentForm, self).save(*args, **kwargs)

tovp/attachments/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.apps import apps
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from attachments.models import Attachment
from attachments.forms import AttachmentForm


def add_url_for_obj(obj):
    return reverse('add_attachment', kwargs={
        'app_label': obj._meta.app_label,
        'model_name': obj._meta.model_name,
        'pk': obj.pk
    })


@login_required
def add_attachment(request, app_label, model_name, pk,
                   template_name='attachments/add.html', extra_context={}):

    model = apps.get_model(app_label, model_name)
    if model is None:
        return HttpResponseRedirect(next)
    obj = get_object_or_404(model, pk=pk)

    next = request.POST.get('next', obj.get_absolute_url())
    if not request.POST:
        form = AttachmentForm()
    else:
        form = AttachmentForm(request.POST, request.FILES)

    if form.is_valid():
        form.save(request, obj)
        messages.success(request, ugettext('Your attachment was uploaded.'))
        return HttpResponseRedirect(next)
    else:
        template_context = {
            'form': form,
            'form_url': add_url_for_obj(obj),
            'next': next,
        }
        template_context.update(extra_context)
        return render(request, template_name, template_context)


@login_required
def delete_attachment(request, attachment_pk):
    g = get_object_or_404(Attachment, pk=attachment_pk)
    if request.user.has_perm('delete_foreign_attachments') \
       or request.user == g.creator:
        g.delete()
        messages.success(request, ugettext('Your attachment was deleted.'))
    next = request.REQUEST.get('next') or '/'
    return HttpResponseRedirect(next)

tovp/attachments/templates/attachments/_attached_files.html
<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-12">
            <h2>Attached Files</h2>
            {% set attachments = get_attachments_for(object) %}
            {% if attachments.count() %}
            <ul>
            {% for attachment in attachments %}
                <li>
                    <a href="{{ attachment.attachment_file.url }}">{{ attachment.get_attachment_type_display() }}</a>
                    {% if attachment.description %}
                        :: {{ attachment.description}}
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
            {% endif %}

            {% if user.has_perm('contributions.add_pledge') %}
                <a href="{{ get_add_attachments_url_for(object) }}" class="btn btn-lg btn-success">Attach file</a>
            {% endif %}
        </div>
    </div>
</div>

tovp/attachments/templates/attachments/add.html
{% extends 'content-area.html' %}
{% set content_title = 'Add attachment' %}
{% set body_class = "person-detail" %}

{% block page_content %}
    {% include "attachments/add_form.html" %}
{% endblock %}

tovp/attachments/templates/attachments/add_form.html
{% if form %}
<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-12 col-sm-12">

            <form method="post" enctype="multipart/form-data" action="{{ form_url }}" class="add-attachment">
                {% if csrf() %}
                {{ csrf() }}
                {% else %}
                <input type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_cookie }}' />
                {% endif %}

                <input type="hidden" name="next" value="{{ next }}"/>

                <div class="row">
                    {% set field_name = 'attachment_type' %}
                    <div class="col-xs-12 col-ms-6 col-sm-4 form-group{{' has-error' if form[field_name].errors }}">
                        <label class="control-label" for="inputSuccess1">{{ form[field_name].label }}</label>
                        {{ form[field_name].errors|safe }}
                        {{form[field_name]|add_css('form-control')}}
                        {% if form[field_name].help_text %}
                        <div class="help-text">
                            {{ form[field_name].help_text }}
                        </div>
                        {% endif %}
                    </div>
                    {% set field_name = 'description' %}
                    <div class="col-xs-12 col-ms-6 col-sm-4 form-group{{' has-error' if form[field_name].errors }}">
                        <label class="control-label" for="inputSuccess1">{{ form[field_name].label }}</label>
                        {{ form[field_name].errors|safe }}
                        {{form[field_name]|add_css('form-control')}}
                        {% if form[field_name].help_text %}
                        <div class="help-text">
                            {{ form[field_name].help_text }}
                        </div>
                        {% endif %}
                    </div>
                    {% set field_name = 'attachment_file' %}
                    <div class="col-xs-12 col-ms-6 col-sm-4 form-group{{' has-error' if form[field_name].errors }}">
                        <label class="control-label" for="inputSuccess1">{{ form[field_name].label }}</label>
                        {{ form[field_name].errors|safe }}
                        {{form[field_name]|add_css('xform-control')}}
                        {% if form[field_name].help_text %}
                        <div class="help-text">
                            {{ form[field_name].help_text }}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <input class="btn btn-lg btn-success" type="submit" value="Save" />
            </form>
        </div>
    </div>
</div>
{% endif %}

tovp/attachments/templates/attachments/delete_link.jinja
{% if delete_url %}<a href="{{ delete_url }}?next={{ next }}">Delete attachment</a>{% endif %}